import sys
import os
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from service.knowledgeGraphService import build_knowledge_graph
from utils.github.client import fetch_file_content_by_sha, is_code_file
from utils.ai.documentation_generator import create_documentation_session
from utils.github.writer import create_branch, create_or_update_file, create_pull_request

def generate_documentation(owner, repository):
    print(f"Building knowledge graph for {owner}/{repository}...")
    graph, nodes_lookup = build_knowledge_graph(owner, repository)

    print("Fetching source code for context...")
    file_contents = _fetch_all_file_contents(owner, repository, graph, nodes_lookup)

    print("Creating documentation session (shared context)...")
    session = create_documentation_session(graph, file_contents)

    folders = _group_nodes_by_folder(graph)
    claude_files = {}

    print("Generating root CLAUDE.md...")
    claude_files["CLAUDE.md"] = session.generate_root_claude_md()

    for folder_path, folder_nodes in folders.items():
        print(f"Generating CLAUDE.md for {folder_path}/...")
        content = session.generate_folder_claude_md(folder_path, folder_nodes)
        claude_files[f"{folder_path}/CLAUDE.md"] = content

    return claude_files


def submit_documentation_pr(owner, repository, claude_files):
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    branch_name = f"docs/auto-claude-md-{timestamp}"

    print(f"Creating branch {branch_name}...")
    create_branch(owner, repository, branch_name)

    for path, content in claude_files.items():
        print(f"  Committing {path}...")
        create_or_update_file(
            owner, repository, path, content,
            message=f"docs: auto-generate {path} from knowledge graph",
            branch=branch_name,
        )

    file_list = "\n".join(f"- `{path}`" for path in claude_files.keys())
    pr_body = (
        "## Auto-generated CLAUDE.md documentation\n\n"
        "Generated by analyzing the repository's knowledge graph:\n"
        "- Parsed all files with tree-sitter to extract symbols and imports\n"
        "- Computed PageRank to identify the most critical files\n"
        "- Read actual source code to provide accurate descriptions\n"
        "- Used LangChain conversation memory for cross-folder consistency\n\n"
        f"### Files created\n{file_list}"
    )

    print("Creating pull request...")
    pr = create_pull_request(
        owner, repository, branch_name,
        title="docs: add CLAUDE.md files generated from knowledge graph",
        body=pr_body,
    )

    return pr.get("html_url", "")

def _fetch_all_file_contents(owner, repository, graph, nodes_lookup):
    file_contents = {}
    for node in graph["nodes"]:
        if node["type"] != "file" or not is_code_file(node["name"]):
            continue
        sha = nodes_lookup.get(node["name"])
        if not sha:
            continue
        try:
            file_contents[node["name"]] = fetch_file_content_by_sha(owner, repository, sha)
        except Exception:
            pass
    return file_contents


def _group_nodes_by_folder(graph):
    folders = {}
    for node in graph["nodes"]:
        if node["type"] != "file":
            continue
        if "/" not in node["name"]:
            continue
        folder = node["name"].rsplit("/", 1)[0]
        folders.setdefault(folder, []).append(node)
    return folders


if __name__ == "__main__":
    owner = "baronliu1993"
    repo = "palettebackend"

    claude_files = generate_documentation(owner, repo)

    print(f"\n=== Generated {len(claude_files)} CLAUDE.md files ===\n")
    for path, content in claude_files.items():
        print(f"--- {path} ---")
        print(content[:500])
        print("...\n")

    confirm = input("Create PR? (y/n): ")
    if confirm.lower() == "y":
        pr_url = submit_documentation_pr(owner, repo, claude_files)
        print(f"\nPR created: {pr_url}")
